[package]
name = "rl_custom_isearch"
version = "0.2.0"
edition = "2021"
authors = [
    "Cheney Lin <lincheney@gmail.com>",
    "David Leibovic <dasl@php.net>",
]
license = "GPL-3.0-or-later"

[dependencies]
libc = "0.2"

[lib]
name = "rl_custom_isearch"
crate-type = ["cdylib"]

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true
